#APP 接口ip
APP_IP: '0.0.0.0'
#APP 接口port
APP_PORT: 9000
##############################################################################
#框架用到的数据库类型:mysql/oracle/mssql/pgsql
DB_TYPE: 'mysql'
###########################进程并发开关############################################
#是否开启多进程并发
IF_CONCURRENCY: False #True\False
#并发进程数量
CONCURRENCY_NUM: 5
###########################光大：是否按task_id去重开关###################################
IF_DUPLICATE_REMOVAL: False #True\False
###########################RABBITMQ###########################################
QUEUE_HOST: '127.0.0.1'
QUEUE_PORT: '5672'
QUEUE_USER: 'guest'
QUEUE_PWD: 'guest'
HEARTBEAT_TIMEOUT: 10
###########################FTP################################################
FTP_IP: '127.0.0.1'
FTP_PORT: 21
FTP_USER: ''
FTP_PWD: ''
###########################LOG################################################
LOG_PATH: 'logs'
LOG_LEVEL: 'INFO' #ERROR、WARN、INFO、DEBUG
###########################CRON JOBS##########################################
#清理语音抽音历史数据定时任务
CRON_JOBS_TIME_SPEECH_DELETE_HISTORY_DATA: False #True\False
CRON_JOBS_TIME_SPEECH_DELETE_HISTORY_DATA_HOUR: '09'
CRON_JOBS_TIME_SPEECH_DELETE_HISTORY_DATA_MINUTE: '30'
CRON_JOBS_TIME_SPEECH_DELETE_HISTORY_DATA_SECOND: '00'
#清理文本抽音历史数据定时任务
CRON_JOBS_TIME_TEXT_DELETE_HISTORY_DATA: False #True\False
CRON_JOBS_TIME_TEXT_DELETE_HISTORY_DATA_HOUR: '09'
CRON_JOBS_TIME_TEXT_DELETE_HISTORY_DATA_MINUTE: '30'
CRON_JOBS_TIME_TEXT_DELETE_HISTORY_DATA_SECOND: '00'
#语音抽音每日自动补数定时任务
CRON_JOBS_TIME_SPEECH_APPEND_DATA: False #True\False
CRON_JOBS_TIME_SPEECH_APPEND_DATA_HOUR: '07'
CRON_JOBS_TIME_SPEECH_APPEND_DATA_MINUTE: '00'
CRON_JOBS_TIME_SPEECH_APPEND_DATA_SECOND: '00'
#文本抽音每日自动补数定时任务
CRON_JOBS_TIME_TEXT_APPEND_DATA: False #True\False
CRON_JOBS_TIME_TEXT_APPEND_DATA_HOUR: '17'
CRON_JOBS_TIME_TEXT_APPEND_DATA_MINUTE: '32'
CRON_JOBS_TIME_TEXT_APPEND_DATA_SECOND: '00'
###########################DB#################################################
mysql:
     mincached: 10
     maxcached: 20
     maxshared: 20
     maxusage: 1000
     maxconnections: 0
     blocking: False
     setsession: None
     host: '127.0.0.1'
     user: 'root'
     passwd: 'Pachira@123'
     db: 'datacapture'
     port: 3306
     charset: 'utf8'

oracle:
     mincached: 10
     maxcached: 20
     host: '172.22.144.126'
     user: 'zls'
     passwd: '1234567'
     sid: 'orcl'
     port: 1521

mssql:
     mincached: 10 #最少的空闲连接数，如果空闲连接数小于这个数，pool会创建一个新的连接
     maxcached: 20 #最大的空闲连接数，如果空闲连接数大于这个数，pool会关闭空闲连接
     maxshared: 20 #当连接数达到这个数，新请求的连接会分享已经分配出去的连接
     maxusage: 1000 #则为一个连接最大使用次数
     maxconnections: 0 #最大允许连接数量 #(0 or None means an arbitrary number of connections)
     blocking: False #达到最大数量时是否阻塞
     setsession: None #用于传递到数据库的准备会话，如 [”set name UTF-8″] ，"set time zone ..."
     host: '192.168.130.241'
     user: 'root'
     passwd: 'admin'
     db: 'datacapture'
     port: 3306
     charset: 'utf8'

pgsql:
     mincached: 1
     maxcached: 4
     maxusage: 1000 # 一个链接最多被重复使用的次数
     maxconnections: 0 # 连接池允许的最大连接数，0 和 None 表示不限制连接数
     blocking: True
     setsession: []
     host: '192.168.130.239'
     user: 'postgres'
     password : 'postgres'
     database : 'datacapture_new'
     port: 5432
