HTTP:
  # 呼叫中心接口url
  DATA_REQUEST_URL: http://gateway.clmp-uat.csleasing.com.cn/hitf/v1/rest/invoke?namespace=HZERO&serverCode=CCUZ.CENTER.CALL&interfaceCode=clmp-customize.udeskcallcentercalllog.queryAllType
  # TOKEN获取URL
  TOKEN_ACCESS_URL: http://gateway.clmp-uat.csleasing.com.cn/oauth/oauth/token?grant_type=client_credentials&client_id=clms-client&client_secret=clms-secret&scope=default
  # 录音质检接口URL
#  RECORD_QC_URL: http://open-dev.csleasing.com.cn/uop/ecar/v1/voice/queryVoice
  RECORD_QC_URL:  http://open.csleasing.com.cn/uop/ecar/v1/voice/queryVoice
  # 按照页数查询
  PAGE_SIZE: 100
  # 录音下载url
  #  RECORD_URL: http://192.168.6.5:8080/AgentRec/
  # 抽音服务内部数据推送接口url
  DATA_RECEIVE_URL: http://localhost:9000/datareceive
  # 推送内部接口单位数据量
  SEND_SIZE: 1000
  # 录音或推送数据保存路径
  DATA_PATH: record_file

QUEUE:
  QUEUE_HOST: 127.0.0.1
  QUEUE_PORT: 5672
  QUEUE_USER: admin
  QUEUE_PWD: admin
  QUEUE_NAME: custom_datacapture_queue

LOG:
  # 日志路径
  LOG_PATH: log

TIMER:
  # 数据抽取定时任务时间
  CAPTURE_SEC: 0
  CAPTURE_MIN: 0
  CAPTURE_HOUR: 1
  # 重推失败数据定时任务时间
  FAILED_SEC: 0
  FAILED_MIN: 0
  FAILED_HOUR: 2
  # 文件清理定时任务时间
  CLEAR_SEC: 0
  CLEAR_MIN: 5
  CLEAR_HOUR: 1
  # 下载的录音文件保存时间
  RECORD_STORAGE_DAYS: 30

# MYSQL数据库连接
MYSQL:
  host: 127.0.0.1
  port: 3306
  user: root
  passwd: Pachira@123
  db: custom_data_capture

# 抽取数据相关的sql
SQL:
  record_sql: ""

# 本地录音路径前缀
PREFIX_PATH: "/mydata/voice/Recording"